# 텐서 (Tensor)
- 배열(array), 행렬(matrix)과 매우 유사한 특수한 자료구조
- GPU나 다른 하드웨어 가속기에서 실행할 수 있음
- 자동 미분(Automatic differentiation)에 최적화

In [1]:
import torch
import numpy as np

### 텐서 초기화

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# 다른 텐서로 부터 재정의 (override)하지 않는다면, 인자로 주어진 텐서의 속성은 다른 텐서와 동일하게 유지
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
#x_data의 속성을 덮어씀
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.0885, 0.2092],
        [0.6830, 0.6538]])

In [6]:
# 무작위, 상수값 사용
# shape: 텐서의 차원
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor : \n {rand_tensor}')
print(f'Ones Tensor : \n {ones_tensor}')
print(f'Zeros Tensor : \n {zeros_tensor}')


Random Tensor : 
 tensor([[0.7397, 0.7812, 0.6184],
        [0.7257, 0.0784, 0.1028]])
Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 속성

In [7]:
tensor = torch.rand(3,4)
print(f'Shape of tensor : {tensor.shape}')
print(f'Datatype of tensor : {tensor.dtype}')
print(f'Device tensor is stored on : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


### 텐서의 연산
- 전치(transpose), 인덱싱, 슬라이싱, 수학계산, 선형대수, 임의 샘플링 등
- 일반적으로 텐서는 CPU에 생성.
- .to 를 이용해 명시적으로 GPU로 이동할 수 있음
- 장치들 간에 큰 텐서들을 복사하는 것은 시간, 메모리 측면에서 비용이 많이 발생

In [8]:
# GPU 존재 시 텐서 이동
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

cpu


In [12]:
# numpy 방식의 표준 인덱싱, 슬라이싱
tensor = torch.ones(4,4)
print(f'First row : {tensor[0]}')
print(f'First column : {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')
tensor[:, 1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
# 산술연산
# 행렬곱(matrix multiplication) -> y1, y2, y3 은 전부 동일한 값을 가짐
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [15]:
# element wise product -> z1, z2, z3은 전부 동일한 값을 가짐
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [16]:
# 단일 요소(single-element)텐서 : 텐서의 모든 값을 하나로 집계
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [18]:
# in-place(바꿔치기) 연산 : 연산 결과를 피연산자에 저장하는 연산, _ 접미사를 가짐
print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


in-place 연산은 메모리를 일부 절약하지만 history가 삭제되어 도함수 계산에 문제가 발생할 수 있음

### Numpy 변환 (Bridge)
- cpu 텐서와 numpy배열은 메모리 공유 -> 하나를 변경하면 다른 하나도 변경됨

In [20]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n : {n}')



t: tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [21]:
n= np.ones(5)
t = torch.from_numpy(n)

In [22]:
# numpy 배열의 변경 사항이 텐서에도 반영됨
np.add(n, 1, out=n)
print(f't : {t}')
print(f'n : {n}')

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
